name: push action

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0

  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Set up Go 1.17.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: go test ./...
